#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Ryuichi Ueda
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

file_path ="numbers.txt"

try:
    with open(file_path, 'r') as file:
        numbers = [line.strip() for line in file.readlines()]
except FileNotFoundError:
    print(f"File '{file.strip}' not found.")
    exit(1)

a = []
ans = 0.0
i = 0
for num in numbers:
    a.append(num)
    try:
        ans += int(num)

    except ValueError:
        try:
            ans += float(num)
        except ValueError:
            print(f"Ignored non number input: {num}")
            i += 1

ma = float(0)
mi = float(100)
for x in a:
    try:
        x = int(x)
        if x > ma:
            ma = x
        if x < mi:
            mi = x
    except ValueError:
        print("no numeric value: {x}")

print(f"total: {math.sqrt(ans)}; maximum: {ma}; minimum: {mi};{i}")

